version: '3.1'
services:
    jenkins:
        image: "lancekuo/jenkins-github-auth:2.118-alpine"
        build: .
        environment:
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:client_id}
            - GITHUB_SECRET_KEY=${GITHUB_SECRET_KEY:secret_key}
            - GITHUB_ADMIN_USERNAME=${GITHUB_ADMIN_USERNAME:user}
            - GITHUB_ORG_NAME=${GITHUB_ORG_NAME:org}
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - /opt/jenkins:/var/jenkins_home
