version: '3.1'
services:
    jenkins:
        image: "jenkins/jenkins:2.103-alpine"
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - /opt/jenkins:/var/jenkins_home
