version: '3.1'
services:
    jenkins:
        image: "jenkins:2.46.3-alpine"
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - /opt/jenkins:/var/jenkins_home
